# This workflows will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: Code Coverage
	
	on: [push]
	
	jobs:
	  deploy:
	
	    runs-on: ubuntu-latest
	
	    steps:
	      - uses: actions/checkout@v1
	      - name: Code coverage-reporter
	        uses: tj-actions/coverage-reporter@v1
	        with:
	          coverage-command: 'python -m coverage report'
