# This workflows will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: Upload Python Package

on: [push]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - name: Python Pylint GitHub Action
      uses: fylein/python-pylint-github-action@v1
    - name: install pip
      run:  sudo apt-get install python3-pip
    - name: checking pylint
      run:  pylint unittestdemo.py

        
