# This workflows will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: Upload Python Package

on:
  release:
    types: [created]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - name: Python Pylin GitHub Action
      uses: fylein/python-pylint-github-action@v1
    - name: Pytnon pip install
      run:  sudo apt-get -y install python3-pip
    - name: install ptlint
      run: sudo apt-get install pylint
    - name: checking pylint for our project
      run: |
        pylint client1.py
        pylint server1.py
